# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: 'Ubuntu 16.04'


variables:
  buildConfiguration: 'Release'
  buildName: "$(TeamProject)_$(Build.DefinitionName)_$(Build.sourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)"

steps:
- script: |
    echo "##vso[build.updatebuildnumber]$(buildName)"
    dotnet build --configuration $(buildConfiguration)
    dotnet test dotnetcore-tests --configuration $(buildConfiguration) --logger trx
    dotnet publish --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishBuildArtifacts@1
